### ISSUE TITLE
tips

### ISSUE THREAD

**Issue by vthinkxie** [yangjunhan/angular-hacker-news#3]
1. interceptor 与 service 拆分开
2. 搞清楚 markForCheck 、 OnPush、zone.js 与 detectChanges 之间的关系，直接在这个 issue 下面回复
ref https://danielwiehl.github.io/edu-angular-change-detection/
ref https://angular.io/guide/zone
3. 在 tsconfig 中增加 paths，使用路径映射 https://www.tslang.cn/docs/handbook/module-resolution.html 将引入的相对地址改为绝对地址
4. 将 page 改为按 module lazyload 加载

**Comment by yangjunhan** [comment]
## 解释markForCheck 、 OnPush、zone.js 与 detectChanges 之间的关系。

首先，**总结一下Angular的change detection的原理**。一般来说，Angular会在以下情况下更新HTML： 

1.  **初始化Component**。在最开始bootstrapping Angular Application的时候，Angular会载入bootstrap component并调用ApplicationRef.tick()方法来触发change detection以及View Rendering。 
2.  **监听事件**。如果DOM的event listener更新了Angular component里面的data，那么change detection就会被触发。 
3.  **HTTP数据请求**。如果在Angular component里更新了请求的数据，那么change detection就会被触发。 
4.  **MacroTasks**。如果在MacroTasks的callback方法里更新了Angular component的数据，那么change detection就会被触发。比如setTimeout(), setInterval()。 
5.  **MicroTasks**。例如Promise.then()里更新了Angular component的数据，那么change detection就会被触发。 
6.  **其他的async operations**。例如WebSocket.onmessage()。 

**关于zone.js**。简单来说，在Zone里面的asynchronous operations的execution context会维持不变。Angular自带了NgZone的service，这个service会创建一个叫‘angular’的Zone。在这个Angular Zone里，当没有schedule MicroTasks或是当执行sync/async function的时候会自动触发change detection。如果Angular的检测策略是的default的，那么所有的asynchronous operations都是在Angular Zone里，并且都会按以上条件自动触发change detection。 

**关于detectChanges()**。虽然Zone可以处理大多数的asynchronous APIs，但是还是有一些Zone无法处理的第三方APIs。当这个第三方APIs的方法update data的时候，这个update是在Angular Zone之外的，所以Angular并不会知道这个update的发生，因此也不会触发change detection。在这个情况下，就可以调用ChangeDetectorRef.detectChanges()来手动触发change detection。除了这个方法外，也可以把调用第三方APIs的codes放入NgZone的zone.run()方法或是放入MacroTasks的setTimeOut()里也都可以手动触发change detection。除此之外，一种适用detectChanges()的情况是当触发了change detection之后又发生了update。总而言之，detectChanges()是用于手动触发change detection的方法之一。 

**关于OnPush和markForCheck()**。如果Angular的检测策略被设置为OnPush，那么只有以下条件下change detection才会被触发： 
1.  当带有@Input property的引用完全变化或是完全被新的值替换的时候。 
2.  当当前component或是child component触发event的时候，例如Click，KeyUp，Subscription等等。 

当有了以上条件限制，很多时候update就不会触发change detection。这时就必须通过调用markForCheck()来手动告诉Angular去检查并更新view。所以总体来说，markForCheck()基本上只在Angular的检测策略被设置为OnPush的时候会被需要使用到。 

最后，总结一下**markForCheck()和detectChanges()的核心区别**。detectChanges()会真正触发Angular的change detection而markForCheck()不会。

**Comment by vthinkxie** [comment]
1. Deep Dive into the Angular Compiler | Alex Rickabaugh
https://www.youtube.com/watch?v=anphffaCZrQ&list=PLAw7NFdKKYpE-f-yMhP2WVmvTH2kBs00s&index=2

2. How we make Angular fast | Miško Hevery
https://www.youtube.com/watch?v=EqSRpkMRyY4&list=PLAw7NFdKKYpE-f-yMhP2WVmvTH2kBs00s&index=10

3. The secrets behind Angular’s lightning speed | Max Koretskyi
https://www.youtube.com/watch?v=nQ8oJ1rpwIc&list=PLAw7NFdKKYpE-f-yMhP2WVmvTH2kBs00s&index=7

4. Performance optimizations in Angular | Mert Değirmenci
https://www.youtube.com/watch?v=Tlmx1PbP8Qw&list=PLAw7NFdKKYpE-f-yMhP2WVmvTH2kBs00s&index=24&t=0s


5. How Angular works | Kara Erickson
https://www.youtube.com/watch?v=S0o-4yc2n-8&list=PLAw7NFdKKYpE-f-yMhP2WVmvTH2kBs00s&index=27&t=1088s

6. Building with Ivy: rethinking reactive Angular | Mike Ryan
https://www.youtube.com/watch?v=rz-rcaGXhGk&list=PLAw7NFdKKYpE-f-yMhP2WVmvTH2kBs00s&index=28&t=4s
